import { StyleSheet } from 'react-native';

import Colors from '../../styles/colors';
import {
  SCREEN_HEIGHT,
  SCREEN_WIDTH,
  normalize,
  normalizeFont,
  normalizeHeight,
} from '../../styles/responsive';

const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    backgroundColor: Colors.dark_grey,
  },
  fullScreenVideo: {
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  connectingWrapper: {
    top: 0,
    left: 0,
    zIndex: 3,
    width: '100%',
    height: '100%',
    position: 'absolute',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: Colors.black,
  },
  connectingText: {
    fontWeight: 'bold',
    color: Colors.secondary,
    marginLeft: normalize(10),
    fontSize: normalizeFont(20),
  },
  safeArea: {
    flex: 1,
  },
  contents: {
    flex: 1,
    alignItems: 'stretch',
  },
  headerView: {
    alignItems: 'center',
    flexDirection: 'row',
    padding: normalize(8),
    backgroundColor: Colors.black,
    borderBottomColor: Colors.grey,
    justifyContent: 'space-between',
    borderBottomWidth: normalize(1),
    paddingHorizontal: normalize(12),
  },
  headerViewBtnWrapper: {
    width: '20%',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  backBtn: {
    width: normalize(40),
    height: normalize(40),
    backgroundColor: Colors.transparent,
  },
  infoBtn: {
    left: '44%',
    right: '44%',
    position: 'absolute',
    alignItems: 'center',
    flexDirection: 'row',
    bottom: normalize(12),
    borderRadius: normalize(5),
    justifyContent: 'space-between',
    paddingVertical: normalizeHeight(6),
  },
  infoBtnText: {
    fontWeight: 'bold',
    color: Colors.white,
    fontSize: normalizeFont(13),
  },
  leaveButton: {
    marginRight: normalize(8),
    borderRadius: normalize(5),
    backgroundColor: Colors.error,
    paddingHorizontal: normalize(16),
    paddingVertical: normalizeHeight(6),
  },
  leaveText: {
    fontWeight: 'bold',
    color: Colors.white,
    fontSize: normalizeFont(12),
  },
  sessionInfo: {
    width: normalize(200),
    padding: normalize(8),
    borderRadius: normalize(8),
    backgroundColor: Colors.black060,
  },
  sessionInfoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sessionName: {
    fontWeight: 'bold',
    color: Colors.secondary,
    fontSize: normalizeFont(16),
  },
  numberOfUsers: {
    color: Colors.secondary,
    fontSize: normalizeFont(13),
  },
  topRightWrapper: {
    alignItems: 'flex-end',
  },
  middleWrapper: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: normalize(8),
  },
  bottomWrapper: (show) => ({
    paddingHorizontal: normalize(8),
    paddingBottom: show ? SCREEN_HEIGHT * 0.1 : normalize(20),
  }),
  videoInfo: {
    alignItems: 'center',
    borderRadius: normalize(8),
    paddingHorizontal: normalize(16),
    backgroundColor: Colors.dark_grey,
    paddingVertical: normalizeHeight(8),
  },
  videoInfoText: {
    color: Colors.secondary,
    fontSize: normalizeFont(12),
  },
  chatList: {
    paddingRight: normalize(16),
  },
  chatMessage: {
    flexDirection: 'row',
    padding: normalize(8),
    alignSelf: 'flex-start',
    borderWidth: normalize(2),
    borderRadius: normalize(8),
    borderColor: Colors.white050,
    marginBottom: normalizeHeight(8),
    backgroundColor: Colors.black060,
  },
  chatUser: {
    color: Colors.silver,
    fontSize: normalizeFont(14),
  },
  chatContent: {
    color: Colors.secondary,
    fontSize: normalizeFont(14),
  },
  controls: {
    alignSelf: 'center',
    paddingTop: normalizeHeight(24),
  },
  controlButton: {
    marginBottom: 12,
  },
  controlBtnStyle: {
    width: normalize(40),
    height: normalize(40),
    backgroundColor: Colors.black060,
  },
  deleteButton: {
    fontSize: 10,
    paddingLeft: 4,
  },
  deleteText: {
    color: Colors.secondary,
  },
  userList: {
    width: '100%',
  },
  userListContentContainer: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  chatInputWrapper: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  chatInput: {
    height: 40,
    marginVertical: 8,
    color: Colors.hit_grey,
    borderColor: Colors.grey,
    borderWidth: normalize(1),
    borderRadius: normalize(6),
    backgroundColor: Colors.black060,
    paddingHorizontal: normalize(16),
  },
  chatSendButton: {
    height: normalizeHeight(36),
  },
  moreListWrapper: {
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
    position: 'absolute',
    padding: normalize(16),
    backgroundColor: Colors.dark_grey,
    borderTopLeftRadius: normalize(10),
    borderTopRightRadius: normalize(10),
  },
  moreList: {
    overflow: 'hidden',
  },
  moreItemText: {
    color: Colors.black,
    textAlign: 'center',
  },
  moreItemWrapper: {
    textAlign: 'center',
    alignItems: 'center',
    padding: normalize(5),
    borderWidth: normalize(1),
    borderRadius: normalize(8),
    fontSize: normalizeFont(90),
    borderColor: Colors.black020,
    paddingVertical: normalize(8),
    marginBottom: normalizeHeight(8),
    paddingHorizontal: normalize(30),
    backgroundColor: Colors.black060,
  },
  cancelButton: {
    alignItems: 'center',
    paddingTop: normalizeHeight(20),
    paddingBottom: normalizeHeight(20),
  },
  cancelButtonText: {
    fontWeight: '700',
    color: Colors.primary,
    fontSize: normalizeFont(18),
  },
  modalContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.black050,
  },
  modal: {
    width: '80%',
    paddingLeft: normalize(24),
    borderRadius: normalize(8),
    paddingRight: normalize(16),
    paddingTop: normalizeHeight(16),
    backgroundColor: Colors.secondary,
    paddingBottom: normalizeHeight(24),
  },
  modalTitleText: {
    fontSize: normalizeFont(18),
    marginBottom: normalizeHeight(14),
  },
  modalActionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: normalizeHeight(20),
  },
  modalActionApply: {
    borderRadius: normalize(4),
    paddingHorizontal: normalize(24),
    backgroundColor: Colors.primary,
    paddingVertical: normalizeHeight(10),
  },
  modalAction: {
    borderRadius: normalize(4),
    paddingHorizontal: normalize(24),
    paddingVertical: normalizeHeight(10),
  },
  modalActionApplyText: {
    fontWeight: '500',
    color: Colors.white,
    fontSize: normalizeFont(14),
  },
  modalActionText: {
    fontWeight: '500',
    color: Colors.dark_grey,
    fontSize: normalizeFont(14),
  },
  moreItem: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: normalizeHeight(16),
    justifyContent: 'space-between',
  },
  moreItemText: {
    fontWeight: '500',
    color: Colors.white,
    fontSize: normalizeFont(16),
  },
  moreItemIcon: {
    width: normalize(36),
    height: normalize(36),
    marginLeft: normalize(48),
  },
  moreModalTitle: {
    fontSize: normalizeFont(24),
  },
  renameInput: {
    width: '100%',
    borderWidth: 1,
    color: Colors.black,
    padding: normalize(8),
    borderRadius: normalize(8),
    fontSize: normalizeFont(14),
    borderColor: Colors.hit_grey,
    marginTop: normalizeHeight(6),
    // borderBottomWidth: normalize(1),
  },
  keyboardArea: {
    width: 0,
    height: 0,
    zIndex: normalizeHeight(-100),
  },
  modalWrapper: {
    flex: 1,
    backgroundColor: Colors?.black060,
  },
  modalOverlay: {
    flex: 1,
  },
  infoModalView: {
    width: SCREEN_WIDTH,
    padding: normalize(16),
    backgroundColor: Colors.dark_grey,
    borderTopLeftRadius: normalize(10),
    borderTopRightRadius: normalize(10),
    paddingVertical: normalizeHeight(20),
  },
  textWrapper: {
    width: '100%',
    flexDirection: 'row',
    borderRadius: normalize(5),
    justifyContent: 'space-between',
    marginBottom: normalizeHeight(8),
    paddingHorizontal: normalize(10),
    backgroundColor: Colors.black060,
    paddingVertical: normalizeHeight(8),
  },
  titleText: {
    width: '100%',
    textAlign: 'center',
    fontWeight: '700',
    color: Colors.white,
    fontSize: normalizeFont(16),
    marginBottom: normalizeHeight(14),
  },
  headerText: {
    color: Colors.off_white,
    fontSize: normalizeFont(14),
  },
  subText: {
    fontWeight: '700',
    color: Colors.white,
    fontSize: normalizeFont(14),
  },
  infoCloseBtn: {
    alignItems: 'center',
    marginTop: normalizeHeight(10),
    paddingVertical: normalizeHeight(10),
  },
  infoCloseBtnText: {
    fontWeight: '700',
    color: Colors.white,
    fontSize: normalizeFont(16),
  },
});

export default styles;
